use crate::span::Span;

/// Token: `kind` + source range (spec §3). Statements are separated by newlines; the lexer emits `Newline` for the parser to consume at statement boundaries.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Token {
    pub kind: TokenKind,
    pub span: Span,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TokenKind {
    Ident(String),
    Symbol(String),
    Integer(String),
    Float(String),
    Hex(String),
    Binary(String),
    Str(String),
    Char(char),
    TexStr(String),

    KwLet,
    KwMut,
    KwConst,
    KwFn,
    KwReturn,
    KwFor,
    KwIn,
    KwWhile,
    KwIf,
    KwElse,
    KwStep,
    KwTry,
    KwCatch,
    KwMatch,
    KwParFor,
    KwConfig,
    KwWith,
    KwPub,
    KwImport,
    KwFrom,
    KwAs,
    KwTrue,
    KwFalse,

    KwAsync,
    KwYield,
    KwMacro,
    KwTrait,
    KwImpl,

    Plus,
    Minus,
    Star,
    Slash,
    Caret,
    DoubleStar,
    Percent,
    At,
    AtDot,
    Eq,
    PlusEq,
    MinusEq,
    EqEq,
    Bang,
    BangEq,
    Lt,
    LtEq,
    Gt,
    GtEq,
    AmpAmp,
    PipePipe,
    Pipe,
    PipeArrow,
    Colon,
    ColonColon,
    ColonEq,
    Arrow,
    FatArrow,
    Comma,
    Semicolon,
    DotDot,
    Underscore,
    LParen,
    RParen,
    LBracket,
    RBracket,
    LBrace,
    RBrace,
    Newline,
    Eof,
}

pub fn describe(kind: &TokenKind) -> String {
    match kind {
        TokenKind::Ident(s) | TokenKind::Symbol(s) => format!("`{s}`"),
        TokenKind::Integer(s)
        | TokenKind::Float(s)
        | TokenKind::Hex(s)
        | TokenKind::Binary(s)
        | TokenKind::Str(s)
        | TokenKind::TexStr(s) => format!("`{s}`"),
        TokenKind::Char(c) => format!("`'{c}'`"),
        TokenKind::KwLet => "`let`".into(),
        TokenKind::KwMut => "`mut`".into(),
        TokenKind::KwConst => "`const`".into(),
        TokenKind::KwFn => "`fn`".into(),
        TokenKind::KwReturn => "`return`".into(),
        TokenKind::KwFor => "`for`".into(),
        TokenKind::KwIn => "`in`".into(),
        TokenKind::KwWhile => "`while`".into(),
        TokenKind::KwIf => "`if`".into(),
        TokenKind::KwElse => "`else`".into(),
        TokenKind::KwStep => "`step`".into(),
        TokenKind::KwTry => "`try`".into(),
        TokenKind::KwCatch => "`catch`".into(),
        TokenKind::KwMatch => "`match`".into(),
        TokenKind::KwParFor => "`parfor`".into(),
        TokenKind::KwConfig => "`config`".into(),
        TokenKind::KwWith => "`with`".into(),
        TokenKind::KwPub => "`pub`".into(),
        TokenKind::KwImport => "`import`".into(),
        TokenKind::KwFrom => "`from`".into(),
        TokenKind::KwAs => "`as`".into(),
        TokenKind::KwTrue => "`true`".into(),
        TokenKind::KwFalse => "`false`".into(),
        TokenKind::KwAsync => "`async`".into(),
        TokenKind::KwYield => "`yield`".into(),
        TokenKind::KwMacro => "`macro`".into(),
        TokenKind::KwTrait => "`trait`".into(),
        TokenKind::KwImpl => "`impl`".into(),
        TokenKind::Plus => "`+`".into(),
        TokenKind::Minus => "`-`".into(),
        TokenKind::Star => "`*`".into(),
        TokenKind::Slash => "`/`".into(),
        TokenKind::Caret => "`^`".into(),
        TokenKind::DoubleStar => "`**`".into(),
        TokenKind::Percent => "`%`".into(),
        TokenKind::At => "`@`".into(),
        TokenKind::AtDot => "`@.`".into(),
        TokenKind::Eq => "`=`".into(),
        TokenKind::PlusEq => "`+=`".into(),
        TokenKind::MinusEq => "`-=`".into(),
        TokenKind::EqEq => "`==`".into(),
        TokenKind::Bang => "`!`".into(),
        TokenKind::BangEq => "`!=`".into(),
        TokenKind::Lt => "`<`".into(),
        TokenKind::LtEq => "`<=`".into(),
        TokenKind::Gt => "`>`".into(),
        TokenKind::GtEq => "`>=`".into(),
        TokenKind::AmpAmp => "`&&`".into(),
        TokenKind::PipePipe => "`||`".into(),
        TokenKind::Pipe => "`|`".into(),
        TokenKind::PipeArrow => "`|>`".into(),
        TokenKind::Colon => "`:`".into(),
        TokenKind::ColonColon => "`::`".into(),
        TokenKind::ColonEq => "`:=`".into(),
        TokenKind::Arrow => "`->`".into(),
        TokenKind::FatArrow => "`=>`".into(),
        TokenKind::Comma => "`,`".into(),
        TokenKind::Semicolon => "`;`".into(),
        TokenKind::DotDot => "`..`".into(),
        TokenKind::Underscore => "`_`".into(),
        TokenKind::LParen => "`(`".into(),
        TokenKind::RParen => "`)`".into(),
        TokenKind::LBracket => "`[`".into(),
        TokenKind::RBracket => "`]`".into(),
        TokenKind::LBrace => "`{`".into(),
        TokenKind::RBrace => "`}`".into(),
        TokenKind::Newline => "newline".into(),
        TokenKind::Eof => "end of file".into(),
    }
}
